### ISSUE TITLE
Loading module from “http://localhost:8069/formio/static/src/js/form/formio_form.js” was blocked because of a disallowed MIME type (“text/plain”)

### ISSUE THREAD

**Issue by huytl81** [novacode-nl/odoo-formio#161] opened 2021-07-29 08:45 UTC
Hi guys,

I encountered an issue which i can't load forms into my page.
When i turn the developer mode on in Chrome/FireFox then it showing the MIME type issue:
1. Loading module from “http://localhost:8069/formio/static/src/js/form/formio_form.js” was blocked because of a disallowed MIME type (“text/plain”).
2. Loading module from “http://localhost:8069/formio/static/src/js/form/backend_app.js” was blocked because of a disallowed MIME type (“text/plain”).

I'm using Pycharm on windows 10.
![2021-07-29_154504](https://user-images.githubusercontent.com/6469063/127461335-f1aadd63-d4c0-4183-a63c-8f613cdc1318.jpg)

**Comment by bobslee** [comment] 2021-07-31 20:22
Hi @huytl81
I don't have any clue about the issue you reported, also never encountered this.

See the template, all assets properly declared.

https://github.com/novacode-nl/odoo-formio/blob/14.0/formio/views/formio_form_templates.xml

Maybe related with your setup, PyCharm, serving Odoo on windows?

**Comment by huytl81** [comment] 2021-08-02 15:52
Hi @bobslee 
What do you mean "Maybe related with your setup, PyCharm, serving Odoo on windows?"
Can you please give me more detail?
Thank you so much.

**Comment by bobslee** [comment] 2021-08-02 17:45
@huytl81 I don't have a clue. Sorry can't help with this, because I can't reproduce this.

I suggest you check:
- other website blocks working?
- works in backend?
- otherwise you need to debug

Please could you close the issue?

**Comment by huytl81** [comment] 2021-08-03 01:36
@bobslee 
Thank you so much, let me check your suggests first then i will reply you.

**Closed** 2021-08-03 01:37 UTC

**Comment by huytl81** [comment] 2021-08-04 05:03
Hi @bobslee 
Just found this thread > https://github.com/golang/go/issues/32350
so it works for me like a charm.
On my local machine, type this command in windows terminal > C:\>reg query HKCR\.js /v "Content Type"
It's showing me the Content Type is "text/plain":
HKEY_CLASSES_ROOT\.js
    Content Type    REG_SZ    text/plain"
so we just need change that to "application/javascript".
Done!
