### ISSUE TITLE
Error while installing in Odoo 15 Enterprise

### ISSUE THREAD

**Issue by skaag** [novacode-nl/odoo-formio#213] opened 2023-01-12 06:07 UTC
While installing in Odoo 15 Enterprise, I'm getting this error:

```
UncaughtClientError > SyntaxError
Uncaught Javascript Error > Unexpected token '<', "<!DOCTYPE "... is not valid JSON
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.<anonymous> (https://{domain.com}/web/assets/9969-bb445b1/web.assets_backend.min.js:601:55)
```

**Comment by bobslee** [comment] 2023-01-12 08:33
@skaag 
I never encountered this error. So I need more info, eg to reproduce somehow.

Please could you provide more info? See following suggestion:

**Run Odoo with "Activate the developer mode (with assets)"**
Put following query string in the URL `?debug=assets`
The error should now contain more info, an uncompressed traceback.
Please share the traceback. Thanks!

**To thinker about the error:**
It's a rather weird error, because the `<!DOCTYPE>` is only present in the serverside rendered XML templates.
See the paths below where the `<!DOCTYPE>` occurs in the `formio` module.
So I don't yet understand why this is obtained as invalid JSON.

```
formio/views/formio_form_templates.xml
7            &lt;!DOCTYPE html&gt;
formio/views/formio_public_templates.xml
7            &lt;!DOCTYPE html&gt;
76           &lt;!DOCTYPE html&gt;
formio/views/formio_builder_templates.xml
7            &lt;!DOCTYPE html&gt;
formio/views/formio_portal_templates.xml
144          &lt;!DOCTYPE html&gt;
```

**Comment by bobslee** [comment] 2023-01-13 19:52
@skaag Do you also experience the issue on Odoo Community?
I don't experience this issue on Enterprise and Community.

**Comment by skaag** [comment] 2023-01-25 20:13
I no longer see errors in the UI itself. I'm not sure what I did, but I did enable debugging with assets and this hasn't changed much. When we click on `Form Builder` in a form object, we get taken to the form builder UI but the content is blank. 

However, I can see this error in the browser console:

```
Uncaught ReferenceError: Formio is not defined
    at App.createBuilder (app.js:37:23)
    at app.js:30:45
```

Above that line in the console, I also have this line which I don't think is related:

```
DevTools failed to load source map: Could not load content for https://ourdomain.com/formio/static/lib/bootstrap/4.1.3/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

So it looks like somehow the formio object is not loaded/instantiated. I'm not sure why.

**Comment by skaag** [comment] 2023-01-25 20:14
I do have a Test/QA environment that I can give you access to if you want to debug this directly. Let me know.

**Comment by bobslee** [comment] 2023-01-25 20:22
Did you downloaded and installed a "formio.js version"?

In the Forms menu, go to Settings and click (button) to download and register new available versions.

You'll need to install at least 1 "formio.JS version" from the "Available GitHub tags" (in Settings menu).
Recommending to use 4.4.x.
Version 5 could still be experimental.

Open the Form Builder(s) and assign the "formio.js version".

Hope this helps. Let me know.

**Comment by skaag** [comment] 2023-01-25 20:41
I generated a PAT in my GitHub, pasted it in, clicked the button and the popup shows up empty. When I navigate here: https://github.com/formio/formio.js/releases there are no releases, but in `Tags` I do see a bunch of tagged versions, but they are pre 5.x versions such as `v4.15.0-rc.17` (which says `Yesterday` in its timestamp).

For some reason the version I have seems to be referencing version `5.0.0-m.16`.

**Comment by bobslee** [comment] 2023-01-25 20:49
Indeed, the GitHub "formio.js" projects doesn't provide releases (atm).

The Odoo app has the functionality to:
- collect and register the tags (so called version).
- download (install) tags
- assign the version to the Form Builder(s).

Did you checked out on the demo (v15) environment?

https://demo15.novacode.nl
User: demo
Pass: demo

I'm off for today. Shall respond tomorrow.

**Comment by bobslee** [comment] 2023-01-26 18:40
Thanks for your update!

Regarding the empty popup by `Check and Register new Versions`.
It's ok. Presumably there're no new versions to register in Odoo.T
he latest versions already had been registered as records shown in the screenshot below.

Also the screenshot shows how to download & install such a version (from the corresponding GitHub tag tarball).

![image](https://user-images.githubusercontent.com/328803/214921523-a5f1be4a-6449-4711-aafc-ad4a64df5ed6.png)

Installed formio.js version should be set in the Form Builder, like the following screenshot.

![image](https://user-images.githubusercontent.com/328803/214921775-be3c0f35-400b-4796-ac00-4b54e9859977.png)

Hope this helps you. Let me know.

**Comment by bobslee** [comment] 2023-01-26 18:50
I tested and reviewed with the Forms (`formio`) module on Odoo 15.0
The admin user (XMLID: `base.user_admin`, id: 2) gets the "Forms Administrator" group upon installation of the module.
So the admin user has (full) access to the Forms app and can use it right away.

If all questions in this issue are resolved, please close this.
Thanks!

**Comment by bobslee** [comment] 2023-01-26 18:53
By the way, there's a scheduled action (cron) which checks and registeres new "formio.js version" every day.

Scheduled action name:
`Forms: Check and register new Versions (GitHub tags)`

**Closed** 2023-01-26 19:58 UTC
Labels: formio (module), need more info

**Comment by bobslee** [comment] 2023-01-26 20:03
Maybe I shall review and improve the permissions assigment for this module.
I'll create an issue for this.

Alright, regarding your issue with the JS library (version 5).
Maybe I had to emphasize that. I pointed out in https://github.com/novacode-nl/odoo-formio/issues/213#issuecomment-1404180328

> Recommending to use 4.4.x.
Version 5 could still be experimental.

**Comment by bobslee** [comment] 2023-01-26 20:33
@skaag ff2b3a9f345919067b81d6f8dd1e83346f9c3102
`[IMP] formio: Ensure users with (group) "Administration Settings" are assigned to the "Forms Administrator" group.`

Version: 11.4
